Titouan
TheDude957/team_name-soen341project2022 pull request #86
Opened 2022-03-16 21:23 UTC by Resident-png

Pretty much finished the sign up page. The only thing left to change (if we want to) is to make sure the email adress isn't already in the database. We might also want to actually check if the password and confirm password are the same.

2022-03-16 21:25 UTC, Resident-png commented
Pull request for work on issues #3 and #72.

2022-03-16 22:04 UTC, shakhal350 approved these changes

2022-03-17 14:36 UTC, tenzabest requested changes
Before merging, make sure to :
-Compare password with confirm password
-Verify that all text fields are completed before sign up 
-Verify if email used to sign up doesn't exist 

Pull request should be done in the working branch
Make sure you have a descriptive commit name

2022-03-17 14:36 UTC, tenzabest commented on src/Components/SignUp.js
>      const handleChangeFN = (event) => {
Change function name
Ex : handleChangeFN should be handleChangeFirstName

2022-03-17 14:36 UTC, tenzabest commented on src/Components/SignUp.js
>      const [firstname, setFirstName] = useState('');
firstName

2022-03-17 14:36 UTC, tenzabest commented on src/Pages/LoginPage.js
> -import SignUp from "../Components/SignUp";
Remove import (Not used)

2022-03-20 20:37 UTC, Resident-png commented
I will close this and do another PR to the working branch

2022-03-20 20:37 UTC, closed without merging